# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2


updates:
  # Updates for Python modules
  - package-ecosystem: "pip"
    directory: "/kiwi_cook_server"
    schedule:
      interval: "daily"
    assignees: ["am9zZWY"]

  # Updates for npm packages
  - package-ecosystem: "npm"
    directory: "/kiwi_cook"
    schedule:
      interval: "daily"
    assignees: ["am9zZWY"]

  # Updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: ["am9zZWY"]
