# https://github.com/actions/labeler

Server:
- all:
  - 'kiwi_cook_server/**/*'

Client:
- all:
  - 'taste_buddy/**/*'
  - 'taste_buddy_ionic/**/*'

Infra:
- all:
  - '.github/**/*'
  - '.vscode/**/*'
