services:
  app:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - DB_CONNSTRING=mongodb://tastebuddy:tastebuddy@mongodb:27017
      - PORT=8081 # (not needed) 8081 is default port for the backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tastebuddy
      - MONGO_INITDB_ROOT_PASSWORD=tastebuddy
