
services:
  app:
    build: ./backend
    ports:
      - "8081:8080"
    environment:
      - DB_CONNSTRING=mongodb+srv://tastebuddyprod.xsyiamo.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority&tlsCertificateKeyFile=mongo-cert.pem
      - PORT=8080
    volumes:
      - ./backend/mongo-cert.pem:/mongo-cert.pem
