services:
  redis:
    image: redis:alpine
    networks:
      - redis_net
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          memory: "128M"

networks:
  app_net:
    driver: bridge
  redis_net:
    driver: bridge
