services:
  taste-buddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: taste-buddy:latest
    container_name: taste-buddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - taste-buddy-network

networks:
  taste-buddy-network:
    driver: bridge
