name: Client Test Build

on:
  push:
    paths:
      - taste_buddy_ionic/**
  pull_request:
    paths:
      - taste_buddy_ionic/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: cd ./client && bun install
    - run: cd ./client && bun run build --if-present
