name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Clean and Build Web
      run: |
        rm -rf build/web
        flutter build web --release

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd build/web
        git init
        git add -A
        git config user.name "taste-buddy"
        git config user.email ""
        git config --local commit.gpgsign false
        git commit -m 'deploy'
        git branch -M master
        git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/taste-buddy/taste-buddy.github.io.git master

    - name: Clean up
      if: always()
      run: |
        cd $GITHUB_WORKSPACE
        rm -rf build/web
