name: Build and Deploy
on:
  push:
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    # install and build project
    - name: Install and Build 🔧
      run: |
        cd ./frontend
        npm ci
        npm run build --if-present

    # deploy to github-pages
    # see here: https://github.com/marketplace/actions/deploy-to-github-pages
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: page
        folder: ./frontend/dist
