name: "Production Server Static Analysis"
on:
  push:
    paths:
      - server-prod/**
  pull_request:
    paths:
      - server-prod/**

jobs:
  ci:
    name: "Run Production Server CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        working-directory: "./server-prod"
